config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'welcome/index'
  root to: 'welcome#index'

  resources :attendees, except: :destroy do
    member { patch 'checkin' }
    member { patch 'uncheckin' }
    member { patch 'reissue' }
    member { patch 'eject' }

    collection { get 'importer' }
    collection { post 'import' }
  end

  resources :attendee_notes, only: %i[new create]

  resources :users, except: %i[new create destroy] do
    member { put 'bless' }
    member { put 'curse' }
  end
end

app/models/attendee.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: attendees
#
#  id                       :bigint           not null, primary key
#  aasm_state               :string
#  address1                 :string
#  address2                 :string
#  area_code                :string
#  badge_name               :string
#  business_name            :string
#  checked_in_at            :datetime
#  checked_in_by            :bigint
#  city                     :string
#  country                  :string
#  ejected_at               :datetime
#  ejected_by               :bigint
#  email                    :string
#  emergency_contact        :string
#  event_name               :string
#  guest_badge              :boolean
#  last_chance_at           :datetime
#  last_chance_by           :bigint
#  last_chance_pay_type     :string
#  legal_name               :string
#  membership_type          :string
#  phone_number             :string
#  preferred_first_name     :string
#  preferred_last_name      :string
#  registered_at            :datetime
#  registrant_legal_name    :string
#  reissued_once_at         :datetime
#  reissued_once_by         :bigint
#  reissued_thrice_at       :datetime
#  reissued_thrice_by       :bigint
#  reissued_thrice_pay_type :string
#  reissued_twice_at        :datetime
#  reissued_twice_by        :bigint
#  reissued_twice_pay_type  :string
#  state                    :string
#  zip                      :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  event_id                 :integer
#  neon_attendee_id         :integer
#  registrant_id            :integer
#  transaction_id           :integer
#
# Indexes
#
#  index_attendees_on_badge_name        (badge_name)
#  index_attendees_on_event_id          (event_id)
#  index_attendees_on_neon_attendee_id  (neon_attendee_id)
#
class Attendee < ApplicationRecord
  include AASM

  has_paper_trail

  aasm timestamps: true do
    state :absent, initial: true, display: 'Not Checked In'
    state :checked_in, display: 'Checked In'
    state :reissued_once, display: 'Checked In (1st Reissue)'
    state :reissued_twice, display: 'Checked In (2nd Reissue)'
    state :reissued_thrice, display: 'Checked In (3rd Reissue)'
    state :last_chance, display: 'Checked In (4th Reissue)'
    state :ejected, display: 'Ejected'

    after_all_transitions :sign_status_change

    event :checkin do
      transitions from: :absent, to: :checked_in
    end

    event :uncheckin do
      transitions to: :absent
    end

    event :reissue do
      transitions from: :checked_in, to: :reissued_once
      transitions from: :reissued_once, to: :reissued_twice
      transitions from: :reissued_twice, to: :reissued_thrice
      transitions from: :reissued_thrice, to: :last_chance
    end

    event :eject do
      transitions to: :ejected
    end
  end

  has_many :attendee_notes, dependent: :destroy

  scope :all_check_ins, -> { where aasm_state: Attendee.checked_in_states }
  scope :reissues, -> { where aasm_state: Attendee.reissued_states }
  scope :ejected, -> { where aasm_state: Attendee::STATE_EJECTED }

  # Membership types are a bit of a hack. Also, for 2021, we only care about Adult and Teen
  scope :adults, -> { where membership_type: 'Adult (Age 18+)' }
  scope :non_adults, -> { where membership_type: ['Teen (Ages 13 to 17)', 'Child (Ages 6 to 12)'] }

  attr_accessor :pay_type, :dummy

  def self.valid_states
    aasm.states.map(&:name)
  end

  def self.pay_states
    [Attendee::STATE_REISSUED_ONCE, Attendee::STATE_REISSUED_TWICE, Attendee::STATE_REISSUED_THRICE]
  end

  def self.reissued_states
    Attendee.pay_states + [Attendee::STATE_LAST_CHANCE]
  end

  def self.checked_in_states
    [Attendee::STATE_CHECKED_IN] + Attendee.reissued_states
  end

  def self.membership_types
    MEMBERSHIP_TYPES
  end

  def printable_membership_type
    case membership_type
    when /^Adult/
      'ADULT'
    when /^Teen/, /^Child/
      'UNDER-18'
    when /^Dealer/
      'ADULT (DEALER)'
    end
  end

  def preferred_name
    "#{preferred_first_name} #{preferred_last_name}".strip
  end

  def dealer?
    membership_type == 'Dealer'
  end

  protected

  def sign_status_change(*args)
    by = args.first[:by]
    by_field = "#{aasm.to_state}_by".to_sym
    pay = args.first[:pay_type]
    pay_field = "#{aasm.to_state}_pay_type".to_sym
    self[by_field] = by.id if by.present? && (has_attribute? by_field)

    self[pay_field] = pay if pay.present? && (has_attribute? pay_field)
  end
end

app/controllers/attendees_controller.rb
# frozen_string_literal: true

class AttendeesController < ApplicationController
  before_action :get_attendee, except: %i[index new create importer import]
  before_action :set_paper_trail_whodunnit

  def index
    redirect_to root_path if current_user.roles.blank?
    @q = policy_scope(Attendee).order(:id).ransack(params[:q])
    @attendees = if params[:q].present?
                   @q.result(distinct: true).page params[:page]
                 else
                   Attendee.none.page params[:page]
                 end
  end

  def show; end

  def new
    @attendee = Attendee.new
    authorize @attendee
  end

  def create
    @attendee = Attendee.new(attendee_params)
    authorize @attendee

    if @attendee.save
      redirect_to @attendee, notice: 'Attendee created!'
    else
      render :new, alert: 'Attendee could not be created!'
    end
  end

  def edit; end

  def update
    if @attendee.update!(attendee_params)
      redirect_to attendee_path(@attendee), notice: 'Attendee updated!'
    else
      render :edit, alert: 'Something is not right!'
    end
  end

  def checkin
    @attendee.checkin! by: current_user
    redirect_to @attendee
  end

  def uncheckin
    @attendee.uncheckin! by: current_user
    redirect_to @attendee
  end

  def reissue
    @attendee.reissue! by: current_user, pay_type: attendee_params[:pay_type]
    redirect_to @attendee
  end

  def eject
    @attendee.eject! by: current_user
    redirect_to @attendee
  end

  def importer
    authorize Attendee
  end

  def import
    authorize Attendee
    @file = attendee_params[:file]
    filename = Rails.root.join('tmp', @file.original_filename)
    File.open(filename, 'wb') do |f|
      f.write(@file.read)
    end
    AttendeeImportJob.perform_later(filename.to_s, current_user)
    redirect_to attendees_path, notice: 'Import in progress'
  end

  protected

  def get_attendee
    @attendee = Attendee.find(params[:id])
    authorize @attendee
  end

  def attendee_params
    permit = %i[pay_type file]

    if current_user.has_any_role? :staff, :helpdesk, :head, :admin
      permit += %i[address1 address2 area_code badge_name
                   city country email emergency_contact
                   guest_badge legal_name membership_type
                   phone_number preferred_first_name preferred_last_name
                   state zip registered_at registered_by]
    end

    params.require(:attendee).permit(permit)
  end
end

app/views/attendees/_attendee.slim
tr
  td= link_to attendee.id, attendee
  td= attendee.badge_name
  td
    - if attendee.legal_name.present?
      = attendee.legal_name 
    - else
      em Registered by #{attendee.registrant_legal_name}
  td= attendee.preferred_name
  td= attendee.guest_badge? ? 'Yes' : 'No'
  td= attendee.registered_at
  td[class="#{attendee.aasm.current_state}"]= attendee.aasm.human_state
  td
    - if attendee.attendee_notes.count.positive?
      i.bi-journal-text

app/views/attendees/_form.slim
.card
  .card-header INSTRUCTIONS
  .card-body
    h5.card-title Transfer
    .card-text
      ol
        li Verify information for origial purchaser
        li Ask attendee for ID and proof of COVID-19 vaccination
        li Update information below
        li Click 'Update Attendee'
    h5.card-title Assign Guest Badge
    .card-text
      ol
        li Follow Transfer instructions above
        li Be sure to uncheck the 'Guest badge' check!
      div.text-danger Note: If there is no 'Guest badge' check, this was not a guest badge! Make sure you have the right entry!

= form_for @attendee do |f|
  - if @attendee.new_record?
    = f.hidden_field :registered_at, value: Time.zone.now

  .fs-3.mb-3 Who
  .row.mb-3
    .col
      = f.label :legal_name, class: 'form-label'
      = f.text_field :legal_name, class: 'form-control'

  .row.mb-3
    .col
      = f.label :preferred_first_name, class: 'form-label'
      = f.text_field :preferred_first_name, class: 'form-control'
    .col
      = f.label :preferred_last_name, class: 'form-label'
      = f.text_field :preferred_last_name, class: 'form-control'

  .row.mb-3
    .col
      = f.label :email, class: 'form-label'
      = f.email_field :email, class: 'form-control'

    .col
      = f.label :badge_name, class: 'form-label'
      = f.text_field :badge_name, class: 'form-control'

  .fs-3.mb-3 What
  .row.mb-3
    .col-2
      = f.label :membership_type, class: 'form-label'
    - if current_user&.has_any_role? :head, :admin
      .col-3
        = f.select :membership_type, options_for_select(Attendee.pluck(:membership_type).uniq.compact.map { |mt| [mt, mt] }), class: 'form-select'
      .col.text-danger
        strong Only Adult and Teen and Dealer are valid for CVG2021
    - else
      .col-3
        div= @attendee.membership_type
      .col.text-danger
        strong Only Heads and Admin can change membership type
  - if @attendee.guest_badge?
    .row.mb-3
      .col-2
        .form-check
          = f.label :guest_badge, class: 'form-check-label'
          = f.check_box :guest_badge, class: 'form-check-input'
      .col.text-danger
        strong Make sure to uncheck this if you're assigning a Guest Of badge to somebody!

  .fs-3.mb-3 Where
  .row.mb-3
    .col
      = f.label :address1, class: 'form-label'
      = f.text_field :address1, class: 'form-control'
  .row.mb-3
    .col
      = f.label :address2, class: 'form-label'
      = f.text_field :address2, class: 'form-control'
  .row.mb-3
    .col
      = f.label :city, class: 'form-label'
      = f.text_field :city, class: 'form-control'
    .col
      = f.label :state, class: 'form-label'
      = f.text_field :state, class: 'form-control'
    .col
      = f.label :zip, class: 'form-label'
      = f.text_field :zip, class: 'form-control'
    .col
      = f.label :country, class: 'form-label'
      = f.text_field :country, class: 'form-control'

  .row.mb-3
    .col= f.submit class: 'btn btn-primary'
    - if @attendee.new_record?
      .col = link_to 'Cancel', attendees_path, class: 'btn btn-secondary'
    - else
      .col= link_to 'Cancel', attendee_path(@attendee), class: 'btn btn-secondary'

app/views/attendees/edit.slim
.container
  .row
    .col
      h1 Edit/Transfer Attendee
  .row
    .col
      = render 'form'

app/views/attendees/importer.slim
.container
  .row
    .col
      h1 Import Attendees
      h2.text-danger Warning: This is not destructive. If you import duplicate data, you will get duplicate data.
      div This will import in the background. Check your mail when it's done.
  .row
    .col
      = form_for :attendee, url: import_attendees_path do |f|
        = f.label for: :file, class: 'form-label'
          | File to import
        = f.file_field :file, class: 'form-control'
        .col
          = f.submit class: 'btn btn-danger form-control'

app/views/attendees/index.slim
.container-fluid
  .card
    .card-header data-bs-toggle="collapse" data-bs-target="#instructions"
      | INSTRUCTIONS (click to expand)
    .card-body.collapse#instructions
      h5.card-title Searching
      ol
        li
          div Fuzzy Search by Badge Name, Legal Name, or Preferred First Name
          div
            strong or
          div Fuzzy Search by Dealer's Name
          div 
            strong or
          div Search by exact Badge Number
        li
          div On a fuzzy search, you may legitimately get multiple record for the same person if
          div
            ul
              li They registered Guest Of badges (should have Guest Badge marked Yes)
              li They accidentally bought more than one badge for themselves
              li They INTENDED to buy a Guest Badge and forgot to mark it as such
        li Select the correct attendee
        li Follow the instructions on the attendee display page

  hr /
  .row
    .col
      = search_form_for @q do |f|
        .row.mb-3
          .col
            = f.label :badge_name_or_legal_name_or_preferred_first_name_or_registrant_legal_name_cont, class: 'form-label' do 
              | Any name field contains
            = f.search_field :badge_name_or_legal_name_or_preferred_first_name_or_registrant_legal_name_cont, class: 'form-control'
        .row.mb-3 
          .col 
            = f.label :business_name, class: 'form-label'
              | Dealer's Business Name contains
            = f.search_field :business_name_cont, class: 'form-control'
        .row.mb-3
          .col
            = f.label :id_eq, class: 'form-label'
              | Badge number equals
            = f.search_field :id_eq, class: 'form-control'
        .row.mb-3
          .col
            = f.submit class: 'btn btn-primary'
  hr/

  = paginate @attendees

  .list-group.list-group-horizontal
    li.list-group-item.text-primary Total Registered: #{Attendee.count}
    li.list-group-item.text-success Checked in (incl. reissues): #{Attendee.all_check_ins.count}
    li.list-group-item.text-warning Reissues: #{Attendee.reissues.count}
    li.list-group-item.text-danger Ejected: #{Attendee.ejected.count}

  - if @attendees.count.zero?
    .row.mt-3
      .col
        strong Enter a search for badge, real, or preferred name, or for exact badge number above
  -else
    .table-responsive
      table.table.table-striped
        tr
          th Badge #
          th Badge Name
          th Legal Name
          th Preferred Name
          th Guest?
          th Registered@
          th Status
          th Notes?
        = render @attendees

    .row
      .col
        = link_to "Back to Main", attendees_url

app/views/attendees/new.slim
.row
  .col
    h1 Create Attendee
    h2.text-danger Be really sure you want to do this!
.row
  .col
    = render 'form'

app/views/attendees/show.slim
.card
  .card-header INSTRUCTIONS
  .card-body
    - if current_user.has_role? :read_only
      h5.card-title You can look but don't touch!
    - else
      - if @attendee.aasm.current_state == Attendee::STATE_ABSENT
        h5.card-title First-time check-in
        .card-text
          ol
            li Ask attendee for ID and proof of COVID-19 vaccination
            li Verify information below
            li If everything matches, find the attendee's badge
            li Click 'Check in'
      - if @attendee.aasm.current_state == Attendee::STATE_CHECKED_IN
        h5.card-title Lost badge re-issue
        .card-text
          div An attendee can have their badge replaced up to four times
          ol
            li Ask attendee for ID and proof of COVID-19 vaccination
            li Verify information below
            li If everything matches, find a blank badge, write the attendee's badge name
                and badge number in the appropriate places.
            li Click 'Reissue'
      - if @attendee.aasm.current_state.in? Attendee.pay_states
        h5.card-title Second - Fourth badge re-issue
        .card-text
          div An attendee can have their badge replaced up to four times
          div After the first reissue, the others cost $5 each, cash or credit
          ol
            li Ask attendee for ID and proof of COVID-19 vaccination
            li Verify information below
            li If everything matches, find a blank badge, write the attendee's badge name
                and badge number in the appropriate places.
            li Select Cash or Credit depending on how they are paying, complete the sale
            li Click 'Reissue'
      - if @attendee.aasm.current_state == Attendee::STATE_LAST_CHANCE
        h5.card-title Attendee has exhausted their reissues
        .card-text
          div An attendee can have their badge replaced up to four times. This attendee has used up all of their reissues.
.mt-3
  .row
    .col-3
      h2 Badge Name
    .col
      .row
        - if @attendee.badge_name.blank?
          h2
            span.text-muted
              ' [no badge name assigned--ASK FOR ONE]
            | (##{@attendee.id.to_s})
        - else
          h2 #{@attendee.badge_name} (##{@attendee.id.to_s})
  - if @attendee.guest_badge?
    .row
      h3.text-info This is a guest-of badge!
  - if @attendee.dealer?
    .row
      h3.text-info This is a dealer's membership badge!
    .row
      .col-3
        h3 Business Name
      .col
        h3= @attendee.business_name
  .row
    .col-3
      h3 Legal Name
    .col
      h3= @attendee.legal_name
  - if @attendee.preferred_first_name.present?
    .row
      .col-3
        h3 Preferred Name
      .col
        h3 #{@attendee.preferred_first_name} #{@attendee.preferred_last_name}
  .row.mt-3
    .col-2
      strong Email
    .col
      = @attendee.email
    .col-2
      strong Phone
    .col
      = "#{@attendee.area_code} #{@attendee.phone_number}"
  .row
    .col-2
      strong Address
    .col
      div= @attendee.address1
      div= @attendee.address2
      div= "#{@attendee.city}, #{@attendee.state} #{@attendee.zip}"
  .row.mt-3
    .col
      .row
        .col
          strong Reg'd at
        .col
          div= @attendee.registered_at
      .row 
        .col 
          strong Reg'd by
        .col
          div= @attendee.registrant_legal_name
    .col-2
      strong NEON #
    .col
      div= @attendee.neon_attendee_id
  .row.mt-3
    .col-2
      strong Status
    .col
      div[class="#{@attendee.aasm.current_state}"]= @attendee.aasm.human_state
  - unless current_user.has_role? :read_only
    .row.mt-3
      .col-6
        - state = @attendee.aasm.current_state
        - data = {}
        - if state == Attendee::STATE_LAST_CHANCE
          strong THIS ATTENDEE MAY NOT RECEIVE AN ADDITIONAL REPLACEMENT BADGE
        - elsif state == Attendee::STATE_EJECTED
          .ejected THIS ATTENDEE HAS BEEN EJECTED OR OTHERWISE EXCLUDED FROM THE CONVENTION
        - else
          - case state
            - when Attendee::STATE_ABSENT
              - link = checkin_attendee_path(@attendee)
              - label = 'Check In'
              - css = 'btn btn-primary'
            - when Attendee::STATE_CHECKED_IN, Attendee::STATE_REISSUED_ONCE, Attendee::STATE_REISSUED_TWICE
              - link = reissue_attendee_path(@attendee)
              - label = 'Reissue'
              - css = 'btn btn-success'
            - when Attendee::STATE_REISSUED_THRICE
              - link = reissue_attendee_path(@attendee)
              - label = 'Reissue'
              - css = 'btn btn-warning'
              - data = { confirm: 'THIS IS THE LAST TIME THIS ATTENDEE CAN RECEIVE A REPLACEMENT BADGE!' }

          = form_for @attendee, url: link do |f|
            .row
              .col
                = f.submit label, id: 'reissue', class: css, disabled: state.in?(Attendee.pay_states), data: data
              .col
                = f.hidden_field :dummy
                - if state.in? Attendee.pay_states
                  .btn-group role="group"
                    = f.radio_button :pay_type, 'cash', class: 'btn-check'
                    = f.label :pay_type_cash, 'Cash', class: 'btn btn-outline-secondary'
                    = f.radio_button :pay_type, 'credit', class: 'btn-check'
                    = f.label :pay_type_credit, 'Credit', class: 'btn btn-outline-secondary'
              javascript:
                let form = document.forms["edit_attendee_#{@attendee.id}"]
                form.addEventListener('change', (e) => {
                  let target = e.target;
                  if (target.value === 'cash' || target.value === 'credit') {
                    document.getElementById('reissue').disabled = false;
                  }
                });

      - if @attendee.aasm.current_state != Attendee::STATE_EJECTED
        - if @attendee.aasm.current_state != Attendee::STATE_ABSENT
          .col
            = link_to 'Reset Attendee', uncheckin_attendee_path(@attendee),
              class: 'btn btn-secondary',
              data: { confirm: 'Are you sure you want to reset this attendee?' },
              method: :patch
        .col
          - if current_user.has_any_role? :head, :admin
            = link_to 'Eject from Convention', new_attendee_note_path({ attendee_note: { attendee_id: @attendee.id, note_type: 'ejection' } }), class: 'btn btn-danger',
              data: { confirm: 'BE SURE YOU HAVE CONFIRMATION FROM A REGISTRATION OR OPERATIONS HEAD OR A DIRECTOR BEFORE PROCEEDING' }
    .row.mt-3
      .col
        = link_to 'Add Note', new_attendee_note_path({ attendee_note: { attendee_id: @attendee.id, note_type: 'general' } }), class: 'btn btn-success'

      - if current_user&.can_transfer? && @attendee.aasm.current_state != Attendee::STATE_EJECTED
        .col
          - label = 'Transfer / Edit'
          - label += ' / Assign Guest' if @attendee.guest_badge?
          = link_to label, edit_attendee_path(@attendee), class: 'btn btn-warning',
            data: { confirm: 'At-con transfers and edits should be vetted by a Department Head or Director' }

  .row
    .col
      = link_to "Return to Main", attendees_path

  hr/

  .accordion
    .accordion_item
      h2.accordion-header
        button.accordion-button data-bs-toggle='collapse' data-bs-target='#notes'
          | Notes (#{@attendee.attendee_notes.count})
      #notes.accordion-collapse.collapse
        .accordion-body
          - @attendee.attendee_notes.each do |n|
            .row
              .col
                .card
                  .card-header
                    - if n.note_type == 'ejection'
                      strong.text-danger> EJECTION NOTE
                    strong At #{n.created_at} by #{n.user&.email} (#{n.user&.name})
                  .card-body
                    .card-text= n.note
    .accordion-item
      h2.accordion-header
        button.accordion-button data-bs-toggle='collapse' data-bs-target='#transitions'
          | Transition Log
      #transitions.accordion-collapse.collapse
        .accordion-body
          - Attendee.valid_states.reject { |s| s ==:absent }.each do |state|
            - at = "#{state}_at".to_sym
            - by = "#{state}_by".to_sym
            - pay = "#{state}_pay_type".to_sym
            - if @attendee.send(at).present?
              .row
                .col-3
                  strong= @attendee.send(at)
                .col
                  div
                    strong> Transitioned to
                    span>[class="#{state}"]= state
                  - if @attendee.send(by).present?
                    div
                      strong> by
                      - user = User.find(@attendee.send(by))
                      span>= "#{user.name} (#{user.email})"
                  - if @attendee.respond_to?(pay) && @attendee.send(pay).present?
                    div
                      strong> paid $5
                      span= @attendee.send(pay)

  .accordion-item
    h2.accordion-header
      button.accordion-button data-bs-toggle='collapse' data-bs-target='#edits'
        | Edit Log
    #edits.accordion-collapse.collapse
      .accordion-body
        - edit_keys = %w(legal_name badge_name preferred_first_name preferred_last_name email guest_badge).freeze
        - @attendee.versions.where(event: 'update').each do |a|
          - next if (a.changeset.keys & edit_keys).empty?
          .row
            .col-3
              strong= a.created_at
            - edit_keys.each do |f|
              - if a.changeset[f].present?
                .col
                  div
                    strong #{f.humanize} Changed
                  div
                    strong> From
                    | #{a.changeset[f].first}
                  div
                    strong> To
                    | #{a.changeset[f].last}