config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'welcome/index'
  root to: 'welcome#index'

  resources :attendees, except: :destroy do
    member { patch 'checkin' }
    member { patch 'uncheckin' }
    member { patch 'reissue' }
    member { patch 'eject' }

    collection { get 'importer' }
    collection { post 'import' }
  end

  resources :attendee_notes, only: %i[new create]

  resources :users, except: %i[new create destroy] do
    member { put 'bless' }
    member { put 'curse' }
  end
end

app/models/attendee_note.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: attendee_notes
#
#  id          :bigint           not null, primary key
#  note        :text
#  note_type   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  attendee_id :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_attendee_notes_on_attendee_id  (attendee_id)
#  index_attendee_notes_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (attendee_id => attendees.id)
#  fk_rails_...  (user_id => users.id)
#
class AttendeeNote < ApplicationRecord
  has_paper_trail

  NOTE_TYPES = %w[general ejection].freeze

  belongs_to :attendee
  belongs_to :user

  validates :note, presence: true, length: { minimum: 10, maximum: 2048 }
  validates :note_type, presence: true, inclusion: { in: NOTE_TYPES }
end

app/controllers/attendee_notes_controller.rb
# frozen_string_literal: true

class AttendeeNotesController < ApplicationController
  before_action :create_attendee_note, only: %i[new create]
  def new; end

  def create
    if @attendee_note.save
      notice = 'Note saved'
      if @attendee_note.note_type == 'ejection'
        @attendee.eject! by: current_user
        notice = 'Attendee ejected!'
      end
      redirect_to @attendee, notice: notice
    else
      render :new, alert: 'There was an error'
    end
  end

  private

  def create_attendee_note
    @attendee = Attendee.find attendee_note_params[:attendee_id]
    @attendee_note = AttendeeNote.new(attendee_note_params.merge(user: current_user))
    authorize @attendee_note
  end

  def attendee_note_params
    params.require(:attendee_note).permit(:attendee_id, :note, :note_type)
  end
end

app/views/attendee_notes/new.html.slim
.container-fluid
  -if @attendee_note.note_type == 'ejection'
    strong.text-danger This attendee is being ejected from the convention. If you meant to do this, enter a reason below. If you did not mean to do this, click cancel!
  .row
    .col-3
      h2 Badge Name
    .col
      .row
        h2= @attendee.badge_name + ' (#' + @attendee.id.to_s + ')'
      - if @attendee.guest_badge?
        h3.text-info This is a guest-of badge!
  .row
    .col-3
      h3 Legal Name
    .col
      h3= @attendee.legal_name
  .row
    .col
      = form_for @attendee_note do |f|
        .row
          .col
            = f.hidden_field :note_type, value: "#{f.object.note_type}"
            = f.hidden_field :attendee_id, value: "#{@attendee.id}"
            = f.label :note, class: 'form-label'
            = f.text_area :note, class: 'form-control'
        .row
          .col
            - button_class = 'btn btn-primary'
            - button_text = 'Create Note'
            - if @attendee_note.note_type == 'ejection'
              - button_class = 'btn btn-danger'
              - button_text = 'Save Note and Eject Attendee!'

            = f.submit button_text, class: button_class
            = link_to 'Cancel', attendee_path(@attendee), class: 'btn btn-secondary'