config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'welcome/index'
  root to: 'welcome#index'

  resources :attendees, except: :destroy do
    member { patch 'checkin' }
    member { patch 'uncheckin' }
    member { patch 'reissue' }
    member { patch 'eject' }

    collection { get 'importer' }
    collection { post 'import' }
  end

  resources :attendee_notes, only: %i[new create]

  resources :users, except: %i[new create destroy] do
    member { put 'bless' }
    member { put 'curse' }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  def home; end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_menu.slim
nav.navbar.navbar-expand-md.navbar-light.bg-light
  .container-fluid
    = link_to 'REGINALD', root_url, class: 'navbar-brand'
    button.navbar-toggler[type='button' data-bs-toggle='collapse' data-bs-target='#navbarMain']
      span.navbar-toggler-icon
    #navbarMain.collapse.navbar-collapse
      ul.navbar-nav.me-autho.mb-2.mb-lg-0
        - if current_user.present?
          - if current_user.has_any_role?(:admin, :head, :helpdesk)
            li.nav-item
              = link_to 'Manage Users', users_path, class: 'nav-link'
            li.nav-item
              = link_to 'New Attendee', new_attendee_path, class: 'nav-link'
          - if current_user.has_role?(:admin)
            li.nav-item
              =link_to 'Import', importer_attendees_path, class: 'nav-link'
          li.nav-item
            = link_to 'Sign out', destroy_user_session_path, class: 'nav-link', method: :delete
        - else
          li.nav-item
            = link_to 'Sign in', new_user_session_path, class: 'nav-link'
          li.nav-item
            = link_to 'Sign up', new_user_registration_path, class: 'nav-link'